### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by pypeaday** [btahir/next-beats#3]
It's barely worth a PR but here's a short compose to avoid multiple docker commands

```
services:
  next-beats:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
```

`docker compose up -d` will build and open for you
